// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJrfOHDiS4s_jD5XJsqhpz_7yiOe5Rw0',
    appId: '1:400161299022:web:605fe78e7d1335e0d3411f',
    messagingSenderId: '400161299022',
    projectId: 'flutterfire-ui-codelab-31d6b',
    authDomain: 'flutterfire-ui-codelab-31d6b.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-31d6b.firebasestorage.app',
    measurementId: 'G-E9KHFLSKES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa8BisFV19-kMjzlEq9WWMgp2U85R6gGk',
    appId: '1:400161299022:android:6ac49a3afcb1aa66d3411f',
    messagingSenderId: '400161299022',
    projectId: 'flutterfire-ui-codelab-31d6b',
    storageBucket: 'flutterfire-ui-codelab-31d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQbGbpj6CQ1AQhGWB2RUj1cODus7axpE',
    appId: '1:400161299022:ios:c44217da858a196ed3411f',
    messagingSenderId: '400161299022',
    projectId: 'flutterfire-ui-codelab-31d6b',
    storageBucket: 'flutterfire-ui-codelab-31d6b.firebasestorage.app',
    androidClientId: '400161299022-ltqtvf4q86cbore5539402equsdp10m0.apps.googleusercontent.com',
    iosClientId: '400161299022-q4s633skku58tml07a1m9siflkutn26l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoggin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQbGbpj6CQ1AQhGWB2RUj1cODus7axpE',
    appId: '1:400161299022:ios:c44217da858a196ed3411f',
    messagingSenderId: '400161299022',
    projectId: 'flutterfire-ui-codelab-31d6b',
    storageBucket: 'flutterfire-ui-codelab-31d6b.firebasestorage.app',
    androidClientId: '400161299022-ltqtvf4q86cbore5539402equsdp10m0.apps.googleusercontent.com',
    iosClientId: '400161299022-q4s633skku58tml07a1m9siflkutn26l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoggin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJrfOHDiS4s_jD5XJsqhpz_7yiOe5Rw0',
    appId: '1:400161299022:web:346eab23c085fb68d3411f',
    messagingSenderId: '400161299022',
    projectId: 'flutterfire-ui-codelab-31d6b',
    authDomain: 'flutterfire-ui-codelab-31d6b.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-31d6b.firebasestorage.app',
    measurementId: 'G-3HQWDSSER9',
  );
}
